# Generated by Django 4.1 on 2022-09-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='photo/')),
                ('poston', models.DateField()),
            ],
        ),
    ]
