# Generated by Django 4.1 on 2022-09-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
