# Generated by Django 4.1 on 2022-09-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('order', models.CharField(choices=[('Cold Drink', 'old Drink'), ('Cold Drink', 'old Drink'), ('Cold Drink', 'old Drink'), ('Cold Drink', 'old Drink')], max_length=200)),
            ],
        ),
    ]
